name: Build Executables

on:
  push:
    tags: ['v*']
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
            ext: ""
          - os: windows-latest  
            name: windows
            ext: ".exe"
          - os: macos-latest
            name: macos
            ext: ""

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.14'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install opencv-python pillow PyQt6 numpy pyinstaller
        
    - name: Build executable
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          pyinstaller --onefile --windowed --name ImageDithering src/main.py
        elif [ "$RUNNER_OS" == "macOS" ]; then
          pyinstaller --onefile --windowed --name ImageDithering --osx-bundle-identifier com.dithering.app src/main.py
        else
          pyinstaller --onefile --name ImageDithering src/main.py
        fi
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ImageDithering-${{ matrix.name }}
        path: dist/
        retention-days: 30
