name: Build Executables

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install opencv-python pillow PyQt6 numpy pyinstaller
    - name: Create dist directory
      run: mkdir -p dist
    - name: Build Linux executable
      run: |
        cd src
        pyinstaller --onefile --name ImageDithering main.py
        cp dist/ImageDithering ../dist/ImageDithering-linux
    - uses: actions/upload-artifact@v4
      with:
        name: ImageDithering-linux
        path: dist/ImageDithering-linux

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install opencv-python pillow PyQt6 numpy pyinstaller
    - name: Create dist directory
      run: mkdir dist
    - name: Build Windows executable
      shell: cmd
      run: |
        cd src
        pyinstaller --onefile --windowed --name ImageDithering main.py
        copy dist\ImageDithering.exe ..\dist\ImageDithering-windows.exe
    - uses: actions/upload-artifact@v4
      with:
        name: ImageDithering-windows
        path: dist/ImageDithering-windows.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install opencv-python pillow PyQt6 numpy pyinstaller
    - name: Create dist directory
      run: mkdir -p dist
    - name: Build macOS executable
      run: |
        cd src
        # На macOS используем onedir вместо onefile для корректной работы
        pyinstaller --onedir --windowed --name ImageDithering --osx-bundle-identifier com.dithering.app main.py
        # Копируем весь .app bundle
        cp -r dist/ImageDithering.app ../dist/
    - uses: actions/upload-artifact@v4
      with:
        name: ImageDithering-macos
        path: dist/ImageDithering.app
