name: Build Executables

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
          - os: windows-latest
            name: windows
          - os: macos-latest
            name: macos

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.14'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install opencv-python pillow PyQt6 numpy pyinstaller

    - name: Build executable
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          pyinstaller --onefile --windowed --name ImageDithering_windows src/main.py
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
          pyinstaller --onefile --windowed --name ImageDithering_macos --osx-bundle-identifier com.dithering.app src/main.py
        else
          pyinstaller --onefile --name ImageDithering_linux src/main.py
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ImageDithering-${{ matrix.name }}
        path: dist/