name: Build Executables

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Самая стабильная версия
    - name: Install dependencies
      run: |
        pip install opencv-python pillow PyQt6 numpy pyinstaller
    - name: Build Linux executable
      run: |
        pyinstaller --onefile --name ImageDithering src/main.py
    - uses: actions/upload-artifact@v4
      with:
        name: ImageDithering-linux
        path: dist/ImageDithering

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Самая стабильная версия
    - name: Install dependencies
      run: |
        pip install opencv-python pillow PyQt6 numpy pyinstaller
    - name: Build Windows executable
      run: |
        pyinstaller --onefile --windowed --name ImageDithering src/main.py
    - uses: actions/upload-artifact@v4
      with:
        name: ImageDithering-windows
        path: dist/ImageDithering.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Самая стабильная версия
    - name: Install dependencies
      run: |
        pip install opencv-python pillow PyQt6 numpy pyinstaller
    - name: Build macOS executable
      run: |
        pyinstaller --onefile --windowed --name ImageDithering --osx-bundle-identifier com.dithering.app src/main.py
    - uses: actions/upload-artifact@v4
      with:
        name: ImageDithering-macos
        path: dist/ImageDithering
