name: Simple CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.14'
        cache: 'pip'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Test imports
      run: |
        cd src
        python -c "
        try:
            import main, error_diffusion, ordered_dithering, palette, randomized, threshold, utils
            print('✅ Все модули успешно импортированы!')
        except Exception as e:
            print(f'❌ Ошибка импорта: {e}')
            exit(1)
        "